version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errchkjson
    - errorlint
    - gocritic
    - misspell
    - nolintlint
    - revive
    - unconvert
    - usestdlibvars
    - wastedassign
