[tools]
buf = "latest"
go = "latest"
"go:golang.org/x/tools/cmd/deadcode" = "latest"
golangci-lint = "latest"
goreleaser = "latest"
protoc = "latest"
protoc-gen-go = "latest"

[tasks.proto]
run = "buf generate"

[tasks.lint]
run = "golangci-lint run"

[tasks.deadcode]
run = "deadcode ./..."
